#!/bin/bash

# --- Configuration ---
# This is the CSV file containing your list of repositories.
# Expected format: Name,URL,Description,Stars,Forks,Watchers,Open Issues,Open PRs,Avg Issue Age (Days),Avg PR Age (Days)
# The script will extract URLs from the second column.
# For backward compatibility, it also supports plain text files with one repo per line.
REPO_LIST_FILE="repos.csv"

# This is the name of the CSV file that will be created with the issue data.
OUTPUT_CSV_FILE="issues_export.csv"

# --- Helper Functions ---

# Function to detect if file is CSV format by checking for header
is_csv_format() {
    local file="$1"
    if [ -f "$file" ]; then
        # Check if first line contains "Name,URL" which indicates CSV format
        head -n 1 "$file" | grep -q "Name,URL"
        return $?
    fi
    return 1
}

# Function to extract repository URL from CSV row
extract_repo_url_from_csv() {
    local csv_row="$1"
    # Extract the second field (URL column) from CSV, handling quoted fields
    echo "$csv_row" | awk -F',' '{
        # Handle quoted fields that might contain commas
        if ($2 ~ /^".*"$/) {
            # Remove surrounding quotes from field 2
            gsub(/^"|"$/, "", $2)
        }
        print $2
    }'
}

# --- Script Logic ---

# Start with a clean slate by removing the old CSV if it exists.
rm -f "$OUTPUT_CSV_FILE"

# Create the new CSV file and write the header row with all the new fields.
echo "Repository,Number,Title,State,StateReason,Author,Assignees,Labels,Milestone,Body,URL,ID,CreatedAt,UpdatedAt,ClosedAt,IsPinned,Closed,CommentsCount,ReactionsCount" > "$OUTPUT_CSV_FILE"

# Check if the repository list file actually exists before trying to read it.
if [ ! -f "$REPO_LIST_FILE" ]; then
    echo "Error: Repository list file not found at '$REPO_LIST_FILE'"
    echo "Please create it and add repositories."
    echo "Expected formats:"
    echo "  - CSV format: Name,URL,Description,... (generated by create_repo_list.sh)"
    echo "  - Plain text: One repository URL or owner/repo per line"
    exit 1
fi

# Detect file format and process accordingly
if is_csv_format "$REPO_LIST_FILE"; then
    echo "📊 Detected CSV format. Reading repository URLs from second column..."
    # Read CSV file, skip header (first line), extract URLs from second column
    tail -n +2 "$REPO_LIST_FILE" | while IFS= read -r csv_row || [[ -n "$csv_row" ]]; do
        # Skip empty lines
        if [[ -z "$csv_row" ]]; then
            continue
        fi
        
        # Extract URL from CSV row
        repo_url=$(extract_repo_url_from_csv "$csv_row")
        
        # Skip if URL extraction failed or is empty
        if [[ -z "$repo_url" ]]; then
            continue
        fi
        
        # Extract 'owner/repo' from full URLs.
        repo_slug=$(echo "$repo_url" | sed -E 's|^(https?://)?(www\.)?github\.com/||' | sed 's|/$||' | sed 's/\.git$//')
        
        echo "Fetching open issues for '$repo_slug'..."
        
        # Use 'gh issue list' to fetch all specified fields.
        # We pipe the output to 'jq' to format it into a CSV row.
        # --arg passes the repository name as a variable into the jq command.
        gh issue list \
          --repo "$repo_slug" \
          --state open \
          --limit 500 \
          --json "number,title,state,stateReason,author,assignees,labels,milestone,body,url,id,createdAt,updatedAt,closedAt,isPinned,closed,comments,reactionGroups" | \
          jq --arg repo_name "$repo_slug" -r '.[] | [
              $repo_name,
              .number,
              .title,
              .state,
              .stateReason // "",
              .author.login // "ghost",
              (.assignees | map(.login) | join("; ")),
              (.labels | map(.name) | join("; ")),
              .milestone.title // "",
              (.body | gsub("\r\n|\n|\r"; " ")),
              .url,
              .id,
              .createdAt,
              .updatedAt,
              .closedAt,
              .isPinned,
              .closed,
              (.comments | length),
              (.reactionGroups | map(.users.totalCount) | add)
          ] | @csv' \
          >> "$OUTPUT_CSV_FILE"
    done
else
    echo "📄 Detected plain text format. Reading repository URLs line by line..."
    # Read the repo list file line by line (original logic for backward compatibility).
    while IFS= read -r repo_line || [[ -n "$repo_line" ]]; do
      # Skip any empty lines or lines that start with # (comments).
      if [[ -z "$repo_line" || "$repo_line" == \#* ]]; then
        continue
      fi

      # Extract 'owner/repo' from full URLs.
      repo_slug=$(echo "$repo_line" | sed -E 's|^(https?://)?(www\.)?github\.com/||' | sed 's|/$||' | sed 's/\.git$//')

      echo "Fetching open issues for '$repo_slug'..."

      # Use 'gh issue list' to fetch all specified fields.
      # We pipe the output to 'jq' to format it into a CSV row.
      # --arg passes the repository name as a variable into the jq command.
      gh issue list \
        --repo "$repo_slug" \
        --state open \
        --limit 500 \
        --json "number,title,state,stateReason,author,assignees,labels,milestone,body,url,id,createdAt,updatedAt,closedAt,isPinned,closed,comments,reactionGroups" | \
        jq --arg repo_name "$repo_slug" -r '.[] | [
            $repo_name,
            .number,
            .title,
            .state,
            .stateReason // "",
            .author.login // "ghost",
            (.assignees | map(.login) | join("; ")),
            (.labels | map(.name) | join("; ")),
            .milestone.title // "",
            (.body | gsub("\r\n|\n|\r"; " ")),
            .url,
            .id,
            .createdAt,
            .updatedAt,
            .closedAt,
            .isPinned,
            .closed,
            (.comments | length),
            (.reactionGroups | map(.users.totalCount) | add)
        ] | @csv' \
        >> "$OUTPUT_CSV_FILE"

    done < "$REPO_LIST_FILE"
fi

echo "✅ Success! All data has been exported to '$OUTPUT_CSV_FILE'"
